# Generated by Django 4.1.2 on 2022-10-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_iteminorder_alter_cart_count_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год производства'),
        ),
    ]
